# Etapa 1: Compilación
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app
# Copiar el pom.xml y descargar dependencias para aprovechar la caché de Docker
COPY pom.xml .
RUN mvn dependency:go-offline
# Copiar el código fuente y compilar el proyecto saltando los tests para agilizar
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Imagen de ejecución (ligera y segura)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Copiar solo el archivo .jar generado en la etapa anterior
COPY --from=build /app/target/*.jar app.jar
# Exponer el puerto del backend
EXPOSE 8080
# Comando para arrancar la aplicación aplicando el perfil de producción
ENTRYPOINT ["java", "-jar", "app.jar"]