# Etapa 1: Compilación
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app

# Copiar el pom.xml usando la ruta correcta desde la raíz
COPY backend/pom.xml .

# Descargar dependencias
RUN mvn dependency:go-offline

# Copiar el código fuente del backend
COPY backend/src ./src

# Compilar generando el .jar
RUN mvn clean package -DskipTests

# Etapa 2: Imagen de ejecución
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]