services:
  postgres:
    image: postgres:16-alpine
    container_name: agro_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - agro_postgres_data:/var/lib/postgresql/data
    networks:
      - agro_network

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: agro_backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - agro_network

volumes:
  agro_postgres_data:

networks:
  agro_network:
    driver: bridge