package com.agroempresa.erp.inventario;

public enum TipoMovimientoInventario {
    ENTRADA_MANUAL,
    SALIDA_POR_VENTA,
    ENTRADA_POR_CANCELACION,
    ENTRADA_POR_DEVOLUCION_VENTA,
    ENTRADA_POR_COMPRA,
    SALIDA_POR_CANCELACION_COMPRA,
    SALIDA_POR_DEVOLUCION_COMPRA,
    AJUSTE_POSITIVO,
    AJUSTE_NEGATIVO
}
