alter table movimientos_inventario drop constraint if exists chk_movimientos_inventario_tipo;

alter table movimientos_inventario
    add constraint chk_movimientos_inventario_tipo check (
        tipo in (
            'ENTRADA_MANUAL',
            'SALIDA_POR_VENTA',
            'ENTRADA_POR_CANCELACION',
            'ENTRADA_POR_DEVOLUCION_VENTA',
            'ENTRADA_POR_COMPRA',
            'SALIDA_POR_CANCELACION_COMPRA',
            'SALIDA_POR_DEVOLUCION_COMPRA',
            'AJUSTE_POSITIVO',
            'AJUSTE_NEGATIVO'
        )
    );

create table devoluciones_venta (
    id bigint generated by default as identity primary key,
    venta_id bigint not null,
    fecha_devolucion timestamp(6) without time zone not null,
    motivo varchar(300) not null,
    total numeric(12, 2) not null,
    creado_en timestamp(6) without time zone not null,
    constraint fk_devoluciones_venta_ventas foreign key (venta_id) references ventas (id),
    constraint chk_devoluciones_venta_total_positivo check (total > 0)
);

create table devolucion_venta_detalles (
    id bigint generated by default as identity primary key,
    devolucion_venta_id bigint not null,
    venta_detalle_id bigint not null,
    producto_id bigint not null,
    cantidad integer not null,
    precio_unitario numeric(12, 2) not null,
    subtotal numeric(12, 2) not null,
    constraint fk_devolucion_venta_detalles_devolucion
        foreign key (devolucion_venta_id) references devoluciones_venta (id) on delete cascade,
    constraint fk_devolucion_venta_detalles_venta_detalle
        foreign key (venta_detalle_id) references venta_detalles (id),
    constraint fk_devolucion_venta_detalles_productos
        foreign key (producto_id) references productos (id),
    constraint chk_devolucion_venta_detalles_cantidad_positiva check (cantidad > 0),
    constraint chk_devolucion_venta_detalles_precio_no_negativo check (precio_unitario >= 0),
    constraint chk_devolucion_venta_detalles_subtotal_no_negativo check (subtotal >= 0)
);

create table devoluciones_compra (
    id bigint generated by default as identity primary key,
    compra_id bigint not null,
    fecha_devolucion timestamp(6) without time zone not null,
    motivo varchar(300) not null,
    total numeric(12, 2) not null,
    creado_en timestamp(6) without time zone not null,
    constraint fk_devoluciones_compra_compras foreign key (compra_id) references compras (id),
    constraint chk_devoluciones_compra_total_positivo check (total > 0)
);

create table devolucion_compra_detalles (
    id bigint generated by default as identity primary key,
    devolucion_compra_id bigint not null,
    compra_detalle_id bigint not null,
    producto_id bigint not null,
    cantidad integer not null,
    costo_unitario numeric(12, 2) not null,
    subtotal numeric(12, 2) not null,
    constraint fk_devolucion_compra_detalles_devolucion
        foreign key (devolucion_compra_id) references devoluciones_compra (id) on delete cascade,
    constraint fk_devolucion_compra_detalles_compra_detalle
        foreign key (compra_detalle_id) references compra_detalles (id),
    constraint fk_devolucion_compra_detalles_productos
        foreign key (producto_id) references productos (id),
    constraint chk_devolucion_compra_detalles_cantidad_positiva check (cantidad > 0),
    constraint chk_devolucion_compra_detalles_costo_positivo check (costo_unitario > 0),
    constraint chk_devolucion_compra_detalles_subtotal_no_negativo check (subtotal >= 0)
);

create index idx_devoluciones_venta_venta_id on devoluciones_venta (venta_id);
create index idx_devoluciones_venta_fecha on devoluciones_venta (fecha_devolucion);
create index idx_devolucion_venta_detalles_devolucion on devolucion_venta_detalles (devolucion_venta_id);
create index idx_devolucion_venta_detalles_venta_detalle on devolucion_venta_detalles (venta_detalle_id);
create index idx_devolucion_venta_detalles_producto on devolucion_venta_detalles (producto_id);

create index idx_devoluciones_compra_compra_id on devoluciones_compra (compra_id);
create index idx_devoluciones_compra_fecha on devoluciones_compra (fecha_devolucion);
create index idx_devolucion_compra_detalles_devolucion on devolucion_compra_detalles (devolucion_compra_id);
create index idx_devolucion_compra_detalles_compra_detalle on devolucion_compra_detalles (compra_detalle_id);
create index idx_devolucion_compra_detalles_producto on devolucion_compra_detalles (producto_id);
