create table categorias (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    descripcion varchar(300),
    activo boolean not null default true,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint uk_categorias_nombre unique (nombre)
);

create table clientes (
    id bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    documento_identidad varchar(20),
    telefono varchar(30),
    email varchar(160),
    direccion varchar(250),
    activo boolean not null default true,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint uk_clientes_documento_identidad unique (documento_identidad)
);

create table proveedores (
    id bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    documento_identidad varchar(20),
    telefono varchar(30),
    email varchar(160),
    direccion varchar(250),
    activo boolean not null default true,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint uk_proveedores_documento_identidad unique (documento_identidad)
);

create table productos (
    id bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    descripcion varchar(500),
    precio_venta numeric(12, 2) not null,
    stock_actual integer not null,
    stock_minimo integer not null,
    activo boolean not null default true,
    categoria_id bigint not null,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint fk_productos_categorias foreign key (categoria_id) references categorias (id),
    constraint chk_productos_precio_venta_no_negativo check (precio_venta >= 0),
    constraint chk_productos_stock_actual_no_negativo check (stock_actual >= 0),
    constraint chk_productos_stock_minimo_no_negativo check (stock_minimo >= 0)
);

create index idx_productos_categoria_id on productos (categoria_id);
create index idx_productos_activo on productos (activo);
create index idx_productos_stock_actual on productos (stock_actual);

create table ventas (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    fecha_venta timestamp(6) without time zone not null,
    estado varchar(30) not null,
    total numeric(12, 2) not null,
    total_pagado numeric(12, 2) not null,
    saldo_pendiente numeric(12, 2) not null,
    estado_pago varchar(30) not null,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint fk_ventas_clientes foreign key (cliente_id) references clientes (id),
    constraint chk_ventas_estado check (estado in ('REGISTRADA', 'CANCELADA')),
    constraint chk_ventas_estado_pago check (estado_pago in ('PENDIENTE', 'PARCIAL', 'PAGADA', 'CANCELADA')),
    constraint chk_ventas_total_no_negativo check (total >= 0),
    constraint chk_ventas_total_pagado_no_negativo check (total_pagado >= 0),
    constraint chk_ventas_saldo_pendiente_no_negativo check (saldo_pendiente >= 0),
    constraint chk_ventas_pago_no_supera_total check (total_pagado <= total)
);

create index idx_ventas_cliente_id on ventas (cliente_id);
create index idx_ventas_estado on ventas (estado);
create index idx_ventas_estado_pago on ventas (estado_pago);
create index idx_ventas_fecha_venta on ventas (fecha_venta);

create table venta_detalles (
    id bigint generated by default as identity primary key,
    venta_id bigint not null,
    producto_id bigint not null,
    cantidad integer not null,
    precio_unitario numeric(12, 2) not null,
    subtotal numeric(12, 2) not null,
    constraint fk_venta_detalles_ventas foreign key (venta_id) references ventas (id),
    constraint fk_venta_detalles_productos foreign key (producto_id) references productos (id),
    constraint chk_venta_detalles_cantidad_positiva check (cantidad > 0),
    constraint chk_venta_detalles_precio_unitario_no_negativo check (precio_unitario >= 0),
    constraint chk_venta_detalles_subtotal_no_negativo check (subtotal >= 0)
);

create index idx_venta_detalles_venta_id on venta_detalles (venta_id);
create index idx_venta_detalles_producto_id on venta_detalles (producto_id);

create table compras (
    id bigint generated by default as identity primary key,
    proveedor_id bigint not null,
    fecha_compra timestamp(6) without time zone not null,
    estado varchar(30) not null,
    total numeric(12, 2) not null,
    total_pagado numeric(12, 2) not null,
    saldo_pendiente numeric(12, 2) not null,
    estado_pago varchar(30) not null,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint fk_compras_proveedores foreign key (proveedor_id) references proveedores (id),
    constraint chk_compras_estado check (estado in ('REGISTRADA', 'CANCELADA')),
    constraint chk_compras_estado_pago check (estado_pago in ('PENDIENTE', 'PARCIAL', 'PAGADA', 'CANCELADA')),
    constraint chk_compras_total_no_negativo check (total >= 0),
    constraint chk_compras_total_pagado_no_negativo check (total_pagado >= 0),
    constraint chk_compras_saldo_pendiente_no_negativo check (saldo_pendiente >= 0),
    constraint chk_compras_pago_no_supera_total check (total_pagado <= total)
);

create index idx_compras_proveedor_id on compras (proveedor_id);
create index idx_compras_estado on compras (estado);
create index idx_compras_estado_pago on compras (estado_pago);
create index idx_compras_fecha_compra on compras (fecha_compra);

create table compra_detalles (
    id bigint generated by default as identity primary key,
    compra_id bigint not null,
    producto_id bigint not null,
    cantidad integer not null,
    costo_unitario numeric(12, 2) not null,
    subtotal numeric(12, 2) not null,
    constraint fk_compra_detalles_compras foreign key (compra_id) references compras (id),
    constraint fk_compra_detalles_productos foreign key (producto_id) references productos (id),
    constraint chk_compra_detalles_cantidad_positiva check (cantidad > 0),
    constraint chk_compra_detalles_costo_unitario_positivo check (costo_unitario > 0),
    constraint chk_compra_detalles_subtotal_no_negativo check (subtotal >= 0)
);

create index idx_compra_detalles_compra_id on compra_detalles (compra_id);
create index idx_compra_detalles_producto_id on compra_detalles (producto_id);

create table movimientos_inventario (
    id bigint generated by default as identity primary key,
    producto_id bigint not null,
    tipo varchar(40) not null,
    cantidad integer not null,
    stock_anterior integer not null,
    stock_nuevo integer not null,
    motivo varchar(250) not null,
    referencia_tipo varchar(80),
    referencia_id bigint,
    creado_en timestamp(6) without time zone not null,
    constraint fk_movimientos_inventario_productos foreign key (producto_id) references productos (id),
    constraint chk_movimientos_inventario_tipo check (
        tipo in (
            'ENTRADA_MANUAL',
            'SALIDA_POR_VENTA',
            'ENTRADA_POR_CANCELACION',
            'ENTRADA_POR_COMPRA',
            'SALIDA_POR_CANCELACION_COMPRA',
            'AJUSTE_POSITIVO',
            'AJUSTE_NEGATIVO'
        )
    ),
    constraint chk_movimientos_inventario_cantidad_positiva check (cantidad > 0),
    constraint chk_movimientos_inventario_stock_anterior_no_negativo check (stock_anterior >= 0),
    constraint chk_movimientos_inventario_stock_nuevo_no_negativo check (stock_nuevo >= 0)
);

create index idx_movimientos_inventario_producto_id on movimientos_inventario (producto_id);
create index idx_movimientos_inventario_tipo on movimientos_inventario (tipo);
create index idx_movimientos_inventario_creado_en on movimientos_inventario (creado_en);
create index idx_movimientos_inventario_referencia on movimientos_inventario (referencia_tipo, referencia_id);

create table pagos_venta (
    id bigint generated by default as identity primary key,
    venta_id bigint not null,
    monto numeric(12, 2) not null,
    metodo_pago varchar(40) not null,
    referencia varchar(120),
    fecha_pago timestamp(6) without time zone not null,
    creado_en timestamp(6) without time zone not null,
    constraint fk_pagos_venta_ventas foreign key (venta_id) references ventas (id),
    constraint chk_pagos_venta_monto_positivo check (monto > 0),
    constraint chk_pagos_venta_metodo_pago check (metodo_pago in ('EFECTIVO', 'TRANSFERENCIA', 'YAPE', 'PLIN', 'TARJETA', 'OTRO'))
);

create index idx_pagos_venta_venta_id on pagos_venta (venta_id);
create index idx_pagos_venta_fecha_pago on pagos_venta (fecha_pago);
create index idx_pagos_venta_metodo_pago on pagos_venta (metodo_pago);

create table pagos_compra (
    id bigint generated by default as identity primary key,
    compra_id bigint not null,
    monto numeric(12, 2) not null,
    metodo_pago varchar(40) not null,
    referencia varchar(120),
    fecha_pago timestamp(6) without time zone not null,
    creado_en timestamp(6) without time zone not null,
    constraint fk_pagos_compra_compras foreign key (compra_id) references compras (id),
    constraint chk_pagos_compra_monto_positivo check (monto > 0),
    constraint chk_pagos_compra_metodo_pago check (metodo_pago in ('EFECTIVO', 'TRANSFERENCIA', 'YAPE', 'PLIN', 'TARJETA', 'OTRO'))
);

create index idx_pagos_compra_compra_id on pagos_compra (compra_id);
create index idx_pagos_compra_fecha_pago on pagos_compra (fecha_pago);
create index idx_pagos_compra_metodo_pago on pagos_compra (metodo_pago);
