create table usuarios (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    password_hash varchar(100) not null,
    nombre varchar(160) not null,
    rol varchar(40) not null,
    activo boolean not null default true,
    creado_en timestamp(6) without time zone not null,
    actualizado_en timestamp(6) without time zone not null,
    constraint uk_usuarios_username unique (username),
    constraint chk_usuarios_rol check (rol in ('ADMIN', 'VENTAS', 'COMPRAS', 'INVENTARIO', 'GERENCIA'))
);

create index idx_usuarios_activo on usuarios (activo);
create index idx_usuarios_rol on usuarios (rol);

create table auditoria_eventos (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    accion varchar(80) not null,
    recurso_tipo varchar(80) not null,
    recurso_id bigint,
    detalle varchar(500),
    creado_en timestamp(6) without time zone not null
);

create index idx_auditoria_eventos_username on auditoria_eventos (username);
create index idx_auditoria_eventos_recurso on auditoria_eventos (recurso_tipo, recurso_id);
create index idx_auditoria_eventos_creado_en on auditoria_eventos (creado_en);
