create table movimientos_caja (
    id bigint generated by default as identity primary key,
    tipo varchar(20) not null,
    monto numeric(12, 2) not null,
    metodo_pago varchar(40) not null,
    referencia varchar(120),
    referencia_tipo varchar(80) not null,
    referencia_id bigint not null,
    fecha_movimiento timestamp(6) without time zone not null,
    creado_en timestamp(6) without time zone not null,
    constraint uk_movimientos_caja_referencia unique (referencia_tipo, referencia_id),
    constraint chk_movimientos_caja_tipo check (tipo in ('INGRESO', 'EGRESO')),
    constraint chk_movimientos_caja_monto_positivo check (monto > 0),
    constraint chk_movimientos_caja_metodo_pago check (metodo_pago in ('EFECTIVO', 'TRANSFERENCIA', 'YAPE', 'PLIN', 'TARJETA', 'OTRO'))
);

create index idx_movimientos_caja_tipo on movimientos_caja (tipo);
create index idx_movimientos_caja_metodo_pago on movimientos_caja (metodo_pago);
create index idx_movimientos_caja_fecha on movimientos_caja (fecha_movimiento);
create index idx_movimientos_caja_referencia on movimientos_caja (referencia_tipo, referencia_id);
