create table cierres_caja (
    id bigint generated by default as identity primary key,
    fecha_desde date not null,
    fecha_hasta date not null,
    cantidad_ingresos bigint not null,
    cantidad_egresos bigint not null,
    total_ingresos numeric(12, 2) not null,
    total_egresos numeric(12, 2) not null,
    saldo_calculado numeric(12, 2) not null,
    saldo_reportado numeric(12, 2) not null,
    diferencia numeric(12, 2) not null,
    observaciones varchar(500),
    cerrado_por varchar(80) not null,
    creado_en timestamp(6) without time zone not null,
    constraint uk_cierres_caja_periodo unique (fecha_desde, fecha_hasta),
    constraint chk_cierres_caja_periodo_valido check (fecha_hasta >= fecha_desde),
    constraint chk_cierres_caja_cantidad_ingresos_no_negativa check (cantidad_ingresos >= 0),
    constraint chk_cierres_caja_cantidad_egresos_no_negativa check (cantidad_egresos >= 0),
    constraint chk_cierres_caja_total_ingresos_no_negativo check (total_ingresos >= 0),
    constraint chk_cierres_caja_total_egresos_no_negativo check (total_egresos >= 0)
);

create index idx_cierres_caja_periodo on cierres_caja (fecha_desde, fecha_hasta);
create index idx_cierres_caja_creado_en on cierres_caja (creado_en);
