create table cierres_caja_metodos (
    id bigint generated by default as identity primary key,
    cierre_caja_id bigint not null,
    metodo_pago varchar(40) not null,
    cantidad_ingresos bigint not null,
    cantidad_egresos bigint not null,
    total_ingresos numeric(12, 2) not null,
    total_egresos numeric(12, 2) not null,
    saldo_calculado numeric(12, 2) not null,
    saldo_reportado numeric(12, 2) not null,
    diferencia numeric(12, 2) not null,
    constraint fk_cierres_caja_metodos_cierre
        foreign key (cierre_caja_id) references cierres_caja (id) on delete cascade,
    constraint uk_cierres_caja_metodo unique (cierre_caja_id, metodo_pago),
    constraint chk_cierres_caja_metodos_cantidad_ingresos_no_negativa check (cantidad_ingresos >= 0),
    constraint chk_cierres_caja_metodos_cantidad_egresos_no_negativa check (cantidad_egresos >= 0),
    constraint chk_cierres_caja_metodos_total_ingresos_no_negativo check (total_ingresos >= 0),
    constraint chk_cierres_caja_metodos_total_egresos_no_negativo check (total_egresos >= 0)
);

create index idx_cierres_caja_metodos_cierre on cierres_caja_metodos (cierre_caja_id);
create index idx_cierres_caja_metodos_metodo on cierres_caja_metodos (metodo_pago);
